/*

#########################################################
# PCSK9I USE IN A LARGE OBSERVATIONAL COHORT   ##########
#########################################################

AUTHOR: SVD

DATE: 11/12/2021

STUDY: PCSK9I USE IN A LARGE OBSERVATIONAL COHORT 

MAIN PURPOSE: TO OBTAIN DRUG FILLS FOR THE COHORT.

FURTHER DETAILS: TO OBTAIN LLT DRUG FILLS FOR THE COHORT.

DB: ORD_DEO_20210005D

VIEWS USED: 


VIEWS CREATED: 


TABLES CREATED: 


------------------------------------------------------------ */

USE ORD_Deo_202010005D

-- MEDS - GET STATINS ACCORDING TO CV DRUG CLASS AND THEN WE CAN GET THAT INTO R 
-- AND THEN DO THE REST.

-- HAVE A DRUG CLASS SID FOR STATINS

SELECT TOP 10*
FROM DFLT.STATIN_SID

-- NOW TO GET THE MED FILLS FOR ALL MY PATIENTS 

CREATE VIEW DFLT.ALI_LLT
AS
SELECT B.PatientSID,
	CAST(B.FillDateTime AS DATE) AS FILLDATE, 
	B.QtyNumeric, B.LocalDrugNameWithDose,B.DaysSupply,C.scrssn,C.visitdate

FROM DFLT.STATIN_SID AS A 

INNER JOIN SRC.RxOut_RxOutpatFill AS B
ON A.LocalDrugSID = B.LocalDrugSID

INNER JOIN DFLT.OUTPAT_ALI_BASECOHORT AS C
ON C.PATIENTSID = B.PATIENTSID

-- SEE THE VIEW AND THEN GET THE TABLES ACCORDING TO DRUG TYPE 

SELECT TOP 100*
FROM DFLT.ALI_LLT

-- SEE THE NUMBER OF PATIENTS THAT HAVE INFO HERE.

SELECT COUNT(DISTINCT(SCRSSN)) -- 985661 PATIENTS ARE ON LLT DURING THIS PERIOD FROM THE PATIENTS THAT IN MY COHORT.
FROM DFLT.ALI_LLT

SELECT COUNT(SCRSSN)
FROM DFLT.ALI_LLT -- 

-- CREATING A TABLE AND THEN SAVE THAT TABLE TO GET INTO R...

SELECT *

INTO DFLT.ALI_LLT_TABLE

FROM DFLT.ALI_LLT

-- AM GOING TO SPLIT THIS INTO DRUG CLASSES AND THEN SAVE THEM AS TABLE ACCORDING TO DRUG

/* THESE HAVE ALL THE DATA FOR STATIN THERAPY
AM GOING TO IDENTIFY NON STATIN LLT BY NAME */

USE ORD_Deo_202010005D

SELECT TOP 10 LocalDrugNameWithDose, LocalDrugSID
FROM CDWWORK.DIM.LocalDrug

--

CREATE VIEW DFLT.EZETIMBE_LOCALDRUGSID
AS
SELECT LOCALDRUGNAMEWITHDOSE, LocalDrugSID
 
FROM CDWWORK.DIM.LocalDrug
	WHERE LOCALDRUGNAMEWITHDOSE LIKE '%EZETIMIBE%'


-- NOW TO GET EZETIMIBE FILLS FOR MY PATIENTS 



SELECT A.LocalDrugNameWithDose,
	CAST(B.FillDateTime AS DATE) AS FILLDATE,
	B.QtyNumeric,B.DaysSupply, C.PatientSID, C.scrssn,
	C.visitdate

INTO DFLT.ALI_EZE_FILLS

FROM DFLT.EZETIMBE_LOCALDRUGSID AS A
	INNER JOIN SRC.RxOut_RxOutpatFill AS B
ON A.LocalDrugSID = B.LocalDrugSID
	INNER JOIN DFLT.OUTPAT_ALI_BASECOHORT AS C
ON B.PatientSID = C.PatientSID


-- FILLS FOR PSCSK9I 

SELECT TOP 10*
FROM DFLT.PCSK9I_SID

-- GET FILLS FOR PCSK9I 

SELECT A.LocalDrugNameWithDose,
	CAST(B.FillDateTime AS DATE) AS FILLDATE,
	B.QtyNumeric,B.DaysSupply, C.PatientSID, C.scrssn,
	C.visitdate

 INTO DFLT.ALI_PCSK9I_FILLS

FROM DFLT.PCSK9I_SID AS A
	INNER JOIN SRC.RxOut_RxOutpatFill AS B
ON A.LocalDrugSID = B.LocalDrugSID
	INNER JOIN DFLT.OUTPAT_ALI_BASECOHORT AS C
ON B.PatientSID = C.PatientSID

