/*

#########################################################
# PCSK9I USE IN A LARGE OBSERVATIONAL COHORT   ##########
#########################################################

AUTHOR: SVD

DATE: 11/12/2021

STUDY: PCSK9I USE IN A LARGE OBSERVATIONAL COHORT 

MAIN PURPOSE: TO OBTAIN THE CLINICAL ENDPOINT OF MORTALITY / MI / STROKE / PAD ENDPOINT ???

FURTHER DETAILS: 

DB: ORD_DEO_20210005D

VIEWS USED: 


VIEWS CREATED: 


TABLES CREATED: 


------------------------------------------------------------ */

USE ORD_Deo_202010005D

-- GET THE VITAL STATUS FOR ALL THE PATIENTS 

SELECT TOP 10*
FROM SRC.VitalStatus_Master

-- GET THE DATA 

CREATE VIEW DFLT.ALI_VITAL_STATUS
AS
SELECT A.ACT_LAST_DT, A.LIVING_IND,B.scrssn

FROM SRC.VitalStatus_Master AS A
INNER JOIN DFLT.OUTPAT_ALI_BASECOHORT AS B
ON A.SCRSSN = B.scrssn
-- THIS TABLE CONTAINS THE VITAL STATUS FOR ALL PATIENTS IN THE ALI STUDY.
-- GET THE VIEW INTO A TABLE. 

SELECT COUNT(DISTINCT(SCRSSN)), LIVING_IND
FROM DFLT.ALI_VITAL_STATUS
GROUP BY LIVING_IND

-- CHECK THE MOST RECENT DATE FOR FOLLOWUP.

SELECT MAX(ACT_LAST_DT)

FROM DFLT.ALI_VITAL_STATUS

-- 

SELECT *
INTO DFLT.ALI_STATUS_TABLE
FROM DFLT.ALI_VITAL_STATUS -- NOW THE TABLE CAN BE IMPORTED TO R.

-- NEED TO IDENTIFY ADMISSIONS FOR MI ...

SELECT DISTINCT 
	A.ICD10SID, A.ICD10CODE
INTO #MISID
FROM CDWWORK.DIM.ICD10 AS  A
	WHERE ICD10CODE LIKE 'I21.%'

-- NOW TO GET THE INPATIENT ADMISSIONS INFORMATION FOR MY COHORT WHERE MI IS THE PRIMARY
-- DIAGNOSIS.

SELECT A.ICD10SID, 
	CAST(A.AdmitDateTime AS DATE) AS ADMIT_DATE,
	C.scrssn, C.visitdate,
	DATEDIFF(DAY, C.VISITDATE, A.ADMITDATETIME) AS MI_DAYS

INTO DFLT.ALI_MI_ADMIT

FROM SRC.Inpat_InpatDischargeDiagnosis AS A
	INNER JOIN #MISID AS B
ON A.ICD10SID = B.ICD10SID
	INNER JOIN DFLT.OUTPAT_ALI_BASECOHORT AS C
ON A.PatientSID = C.PatientSID
	WHERE C.visitdate < A.AdmitDateTime AND 
	A.AdmitDateTime < '2020-05-01' AND 
	DATEDIFF(DAY, C.VISITDATE, A.ADMITDATETIME) > 7

-- FEE BASED INFORMATION FOR ADMISSION OUTSIDE AND CAPTURED IN THE VA

SELECT TOP 10*
FROM SRC.Fee_FeeInpatInvoice

SELECT TOP 10*
FROM SRC.Fee_FeeInpatInvoiceICDDiagnosis

-- THESE TWO TABLES TOGETHER CONTAIN THE INFORMATION NEEDED TO IDENTY OUTSIDE
-- ADMISSIONS PAID BY THE VA.

SELECT A.ICD10SID,
	CAST(C.TreatmentFromDateTime AS DATE) AS ADMIT_DATE,
	D.scrssn, D.visitdate

INTO DFLT.ALI_MI_ADMIT_FEEBASED

FROM SRC.Fee_FeeInpatInvoiceICDDiagnosis AS A
	INNER JOIN #MISID AS B
ON A.ICD10SID = B.ICD10SID
	INNER JOIN SRC.Fee_FeeInpatInvoice AS C
ON A.FeeInpatInvoiceSID =  C.FeeInpatInvoiceSID
	INNER JOIN DFLT.OUTPAT_ALI_BASECOHORT AS D
ON C.PatientSID = D.PatientSID 
	WHERE C.TreatmentFromDateTime > D.visitdate
	AND DATEDIFF(DAY, D.VISITDATE, C.TREATMENTFROMDATETIME) >= 7
	AND C.TreatmentFromDateTime < '2020-05-01'

-- NOW TO GET MI ADMITS FROM ER DATA... THIS IS AVAILABLE IN THE STROKE/TIA
-- CODE FROM TIA_STROKE_EVENT 

SELECT TOP 10*

FROM SRC.EDIS_EDISLog 

-- NOW TO GET STROKE ADMITS FOR ALL PATIENTS.



